extends Node

const DMG_TYPE_NAMES: Dictionary = {
	CARD_ENUM.DMG_TYPE.DIRECT: "DIRECT",
	CARD_ENUM.DMG_TYPE.WATER: "WATER",
	CARD_ENUM.DMG_TYPE.FIRE: "FIRE",
	CARD_ENUM.DMG_TYPE.PHYSICAL: "PHYSICAL",
	CARD_ENUM.DMG_TYPE.EARTH: "EARTH",
	CARD_ENUM.DMG_TYPE.WIND: "WIND",
	CARD_ENUM.DMG_TYPE.ELETRICITY: "ELETRICITY",
	CARD_ENUM.DMG_TYPE.ICE: "ICE",
	CARD_ENUM.DMG_TYPE.LIGHT: "LIGHT",
	CARD_ENUM.DMG_TYPE.DARK: "DARK"
}
