extends Node

const DMG_TYPE_NAMES: Dictionary = {
	CARD_ENUM.DMG_TYPE.DIRECT: "DIRECT",
	CARD_ENUM.DMG_TYPE.WATER: "WATER",
	CARD_ENUM.DMG_TYPE.FIRE: "FIRE",
	CARD_ENUM.DMG_TYPE.PHYSICAL: "PHYSICAL",
	CARD_ENUM.DMG_TYPE.EARTH: "EARTH",
	CARD_ENUM.DMG_TYPE.WIND: "WIND",
	CARD_ENUM.DMG_TYPE.ELETRICITY: "ELETRICITY",
	CARD_ENUM.DMG_TYPE.ICE: "ICE",
	CARD_ENUM.DMG_TYPE.LIGHT: "LIGHT",
	CARD_ENUM.DMG_TYPE.DARK: "DARK"
}

const NORMAL_CARD_SCALE = Vector2(0.5, 0.5)
const HIGHLIGHT_CARD_SCALE = Vector2(0.6, 0.6)
const DRAGGED_CARD_SCALE = Vector2(0.8, 0.8)

const HIGHLIGHT_CARD_Z_INDEX = 2
const DRAGGED_CARD_Z_INDEX = 100
const NORMAL_CARD_Z_INDEX = 0
