extends Node

const DMG_TYPE_NAMES: Dictionary = {
	CARD_ENUM.DMG_TYPE.DIRECT: "DIRECT",
	CARD_ENUM.DMG_TYPE.WATER: "WATER",
	CARD_ENUM.DMG_TYPE.FIRE: "FIRE",
	CARD_ENUM.DMG_TYPE.PHYSICAL: "PHYSICAL",
	CARD_ENUM.DMG_TYPE.EARTH: "EARTH",
	CARD_ENUM.DMG_TYPE.WIND: "WIND",
	CARD_ENUM.DMG_TYPE.ELETRICITY: "ELETRICITY",
	CARD_ENUM.DMG_TYPE.ICE: "ICE",
	CARD_ENUM.DMG_TYPE.LIGHT: "LIGHT",
	CARD_ENUM.DMG_TYPE.DARK: "DARK"
}

# size
const NORMAL_CARD_SIZE = Vector2(220, 370)


# scale
const NORMAL_CARD_SCALE = Vector2(0.4, 0.4)
const HIGHLIGHT_CARD_SCALE = Vector2(0.5, 0.5)
const DRAGGED_CARD_SCALE = Vector2(0.6, 0.6)
const SLOT_SCALE = NORMAL_CARD_SCALE * 1.05
const CARD_IN_SLOT_SCALE = Vector2(1, 1)

# z index
const HIGHLIGHT_CARD_Z_INDEX = 2
const DRAGGED_CARD_Z_INDEX = 100
const NORMAL_CARD_Z_INDEX = 0
const CARD_IN_SLOT_Z_INDEX = -1
const SLOT_Z_INDEX = -2
