extends Node

const DMG_TYPE_NAMES = {
	[Enums.DMG_TYPE.WATER]: "WATER",
	[Enums.DMG_TYPE.FIRE]: "FIRE",
	[Enums.DMG_TYPE.PHYSICAL]: "PHYSICAL",
	[Enums.DMG_TYPE.EARTH]: "EARTH",
	[Enums.DMG_TYPE.WIND]: "WIND",
	[Enums.DMG_TYPE.ELETRICITY]: "ELETRICITY",
	[Enums.DMG_TYPE.ICE]: "ICE",
	[Enums.DMG_TYPE.LIGHT]: "LIGHT",
	[Enums.DMG_TYPE.DARK]: "DARK"
}
